runtime: nodejs18

handlers:
  - url: /
    static_files: dist/chaveiro-express/browser/index.html
    upload: dist/chaveiro-express/browser/index.html
    http_headers:
      Cache-Control: public, max-age=0, must-revalidate

  - url: /(.*\.(css|js|png|jpg|jpeg|gif|svg|ico|txt|xml|json|webp|woff|woff2|ttf|eot))
    static_files: dist/chaveiro-express/browser/\1
    upload: dist/chaveiro-express/browser/(.*\.(css|js|png|jpg|jpeg|gif|svg|ico|txt|xml|json|webp|woff|woff2|ttf|eot))
    http_headers:
      Cache-Control: public, max-age=31536000, immutable

  - url: /.*
    static_files: dist/chaveiro-express/browser/index.html
    upload: dist/chaveiro-express/browser/index.html
    http_headers:
      Cache-Control: public, max-age=0, must-revalidate

